[

        {
            "category": "Beef",
            "type": "Brisket",
            "cfiatemp": "145",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "180",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "5",
            "cookingnotes": "",
            "src": "Images/beef.jpg"
        },
        {
            "category": "Beef",
            "type": "Ribs",
            "cfiatemp": "145",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "175",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "240",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/beef.jpg"
        },
        {
            "category": "Beef",
            "type": "Steak",
            "cfiatemp": "145",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "140",
            "ctemprare": "125",
            "ctempwell": "160",
            "ctime": "9",
            "ctimerare": "7",
            "ctimewell": "10",
            "thickness": "1",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/beef.jpg"
        },
        {
            "category": "Beef",
            "type": "Steak",
            "cfiatemp": "145",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "140",
            "ctemprare": "125",
            "ctempwell": "160",
            "ctime": "10",
            "ctimerare": "8",
            "ctimewell": "12",
            "thickness": "1.5",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/beef.jpg"
        },
        {
            "category": "Beef",
            "type": "Steak",
            "cfiatemp": "145",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "140",
            "ctemprare": "125",
            "ctempwell": "160",
            "ctime": "17",
            "ctimerare": "15",
            "ctimewell": "19",
            "thickness": "2",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/beef.jpg"
        },
        {
            "category": "Burgers",
            "type": "Hamburgers",
            "cfiatemp": "160",
            "usdatemp": "160",
            "resttime": "",
            "ctemp": "140",
            "ctemprare": "125",
            "ctempwell": "160",
            "ctime": "5",
            "ctimerare": "4",
            "ctimewell": "7",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/burger.jpg"

        },
        {
            "category": "Burgers",
            "type": "Pork",
            "cfiatemp": "160",
            "usdatemp": "145",
            "resttime": "",
            "ctemp": "160",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "9",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/burger.jpg"
        },
        {
            "category": "Burgers",
            "type": "Turkey",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "180",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/burger.jpg"
        },
        {
            "category": "Burgers",
            "type": "Vegetarian",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "8",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/burger.jpg"
        },
        {
            "category": "Chicken",
            "type": "Breast",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "180",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/chicken.jpg"
        },
        {
            "category": "Chicken",
            "type": "Breast (Bone in)",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "180",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/chicken.jpg"
        },
        {
            "category": "Chicken",
            "type": "Thigh",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "180",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/chicken.jpg"
        },
        {
            "category": "Chicken",
            "type": "Thigh (Bone in)",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "180",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/chicken.jpg"
        },
        {
            "category": "Chicken",
            "type": "Whole",
            "cfiatemp": "165",
            "usdatemp": "165",
            "resttime": "",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "180",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "Insert meat thermometer in thigh to test.",
            "src": "Images/chicken.jpg"
        },
        {
            "category": "Fish",
            "type": "Filet&Steaks",
            "cfiatemp": "158",
            "usdatemp": "145",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "5",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "0.5",
            "weight": "",
            "cookingnotes": "Cook until flesh is opaque and separates easily with a fork.",
            "src": "Images/fish.jpg"
        },
        {
            "category": "Fish",
            "type": "Filet&Steaks",
            "cfiatemp": "158",
            "usdatemp": "145",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "7",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "0.75",
            "weight": "",
            "cookingnotes": "Cook until flesh is opaque and separates easily with a fork.",
            "src": "Images/fish.jpg"
        },
        {
            "category": "Fish",
            "type": "Filet&Steaks",
            "cfiatemp": "158",
            "usdatemp": "145",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "1",
            "weight": "",
            "cookingnotes": "Cook until flesh is opaque and separates easily with a fork.",
            "src": "Images/fish.jpg"
        },
        {
            "category": "Pork",
            "type": "Baby Back Ribs",
            "cfiatemp": "",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "170",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "200",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/pork.jpg"
        },
        {
            "category": "Pork",
            "type": "Boston Butt",
            "cfiatemp": "",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "200",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/pork.jpg"
        },
        {
            "category": "Pork",
            "type": "Chops",
            "cfiatemp": "",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "145",
            "ctemprare": "",
            "ctempwell": "170",
            "ctime": "12",
            "ctimerare": "",
            "ctimewell": "16",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/pork.jpg"
        },
        {
            "category": "Pork",
            "type": "Roast",
            "cfiatemp": "",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "145",
            "ctemprare": "",
            "ctempwell": "170",
            "ctime": "40",
            "ctimerare": "25",
            "ctimewell": "",
            "thickness": "",
            "weight": "1",
            "cookingnotes": "",
            "src": "Images/pork.jpg"
        },
        {
            "category": "Pork",
            "type": "Tenderloin",
            "cfiatemp": "",
            "usdatemp": "145",
            "resttime": "3",
            "ctemp": "150",
            "ctemprare": "",
            "ctempwell": "155",
            "ctime": "24",
            "ctimerare": "18",
            "ctimewell": "",
            "thickness": "",
            "weight": "1",
            "cookingnotes": "",
            "src": "Images/pork.jpg"
        },
        {
            "category": "Sausages and Dogs",
            "type": "Bratwurst",
            "cfiatemp": "165",
            "usdatemp": "140",
            "resttime": "",
            "ctemp": "160",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/dog.jpg"
        },
        {
            "category": "Sausages and Dogs",
            "type": "Hot Dog",
            "cfiatemp": "165",
            "usdatemp": "140",
            "resttime": "",
            "ctemp": "140",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "8",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/dog.jpg"
        },
        {
            "category": "Sausages and Dogs",
            "type": "Italian Sausage",
            "cfiatemp": "165",
            "usdatemp": "140",
            "resttime": "",
            "ctemp": "160",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/dog.jpg"
        },
        {
            "category": "Sausages and Dogs",
            "type": "Vegetarian",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "7",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/dog.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Asparagus",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "11",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Bell Peppers",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Corn (cob)",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "8",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Egg Plant",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Potatoes â€“ Sliced",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "15",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Potatoes â€“ whole",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "40",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Zucchini-Halves",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "12",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        },
        {
            "category": "Vegetables",
            "type": "Zucchini-Sliced",
            "cfiatemp": "",
            "usdatemp": "",
            "resttime": "",
            "ctemp": "",
            "ctemprare": "",
            "ctempwell": "",
            "ctime": "10",
            "ctimerare": "",
            "ctimewell": "",
            "thickness": "",
            "weight": "",
            "cookingnotes": "",
            "src": "Images/vegetables.jpg"
        }

  ]
